CREATE TABLE logs(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    date_log DATETIME NOT NULL,
    id_user INTEGER UNSIGNED DEFAULT NULL,
    type ENUM('INFO','NOTICE','WARN','ERROR') NOT NULL DEFAULT 'INFO',
    comment TEXT DEFAULT '',
    FOREIGN KEY(id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX(type),
    PRIMARY KEY(id)
) ENGINE=InnoDB;
